name: Uppgift 1

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: "Ange ditt namn"
        default: "Okänd användare"

jobs:
  jobs-for-main-user:
    if: ${{ github.event.inputs.user_name == 'erik' }}
    runs-on: ubuntu-latest
    steps:
      - name: Visa användarens input
        run: echo "hej erik!"

  jobs-for-other-user:
    if: ${{ github.event.inputs.user_name != 'erik' }}
    runs-on: ubuntu-latest
    steps:
      - name: Visa användarens input
        run: echo "hej gäst!"




  

   




